name: Release and Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-metadata-file: 'pyproject.toml'
          python-version: '3.10'

      - name: Package Source
        run: |
          zip -r stable-diffusion-qnn-source.zip . -x "models/*" "venv*" "output.png" ".git/*" ".github/*"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: stable-diffusion-qnn-source.zip
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
